Добавил кастомный компонент Визитка
turboext/components pull request #1
Opened 2019-04-08 21:17 UTC by sbmaxx

2019-04-10 11:57 UTC, notary commented
@sbmaxx в целом норм, можно конечно подробить render на несколько функций
Но если для вас не проблема работать с таким количеством строк в одной функции, то мы не против

2019-04-10 12:23 UTC, notary submitted a review, later dismissed

2019-04-10 12:26 UTC, werreour requested changes

2019-04-10 12:26 UTC, werreour commented on components/ExtYandexBusinessCard/ExtYandexBusinessCard.scss
> +  src: url(data:application/font-woff2;base64,d09GMgABAAAAAJwMABEAAAAB+EwAAJunAAEAQgAAAAAAAAAAAAAAAAAAAAAAAAAAG4KoZhyiQAZgFotgAJIKCE4JgnMRDAqEoESD6i4BNgIkA5UgC4pSAAQgBY4VB6tBDIVaW7TWcQfdtt8QtaLcNgCGm
точно ли нужен шрифт? Размер `css` файла в 53 `kb`

2019-04-11 07:38 UTC, werreour approved these changes

2019-04-11 09:04 UTC, notary approved these changes

2019-04-11 09:05 UTC, merged

2019-04-15 09:44 UTC, werreour commented
@sbmaxx 
Вы в продакшн. Компонент можно использовать на своих страницах.