Добавлен компонент рекомендательного сервиса Strossle
turboext/components pull request #19
Opened 2019-10-21 15:21 UTC by Serzhenka

`data-widget` - уникальный id виджета Strossle для паблишера
`data-url` - путь до виджета Strossle на стороне паблишера

2019-10-22 11:39 UTC, notary commented
Привет!

Спасибо за желание быть в рядах разработчиков, кто попробует функциональность Турбо-страниц — пользовательские блоки.

По пулл-реквесту.
К сожалению текущее решение с передачей src скрипта через rss не может быть использовано, так как потенциально несет xss уязвимости. Подскажите, нет ли возможности использовать единственный  url для работы компонента?

2019-10-22 13:48 UTC, Serzhenka commented
> Привет!
> 
> Спасибо за желание быть в рядах разработчиков, кто попробует функциональность Турбо-страниц — пользовательские блоки.
> 
> По пулл-реквесту.
> К сожалению, текущее решение с передачей src скрипта через rss не может быть использовано, так как потенциально несет xss уязвимости. Подскажите, нет ли возможности использовать единственный url для работы компонента?

@notary Спасибо за ответ.
Согласно описанию `data-url` будет содержать путь на скрипт размещенный на домене паблишера, но сами материалы (ассеты), будут и могут подгружаться только со стороннего домена, так как это сервис рекомендаций, который может включать в себя и ассеты рекламодателей.

Но есть другое предложение - можно зафиксировать/вшить конкретный скрипт (убрав `data-url`), который будет отрабатывать и отрисовывать виджет, вот он:
`https://widgets.sprinklecontent.com/v2/sprinkle.js`

И в компонент будет приниматься только один параметр - `data-widget`, далее скрипт выше подхватит id и отрисует виджет.
Подскажите, исключение для данного скрипта сможете утвердить на вашей стороне?

2019-10-24 09:48 UTC, sbmaxx commented
Привет!

> Подскажите, исключение для данного скрипта сможете утвердить на вашей стороне?

К сожалению, подключение внешних скриптов существенно снижает уровень безопасности пользователей Турбо-страниц. Тут недостаточно просто зафиксировать URL, т.к. никто не гарантирует, как будет изменяться его содержимое. Правильный вариант в этом случае — sandboxing. 

Мы сейчас обсуждаем различные варианты решения внутри, и скоро вернёмся с ответом.

2019-11-19 09:29 UTC, Serzhenka commented
@sbmaxx @notary Ping.
Ребята привет! Очень ждем вас здесь.

2020-01-10 08:56 UTC, notary commented
Привет!

Спасибо за ожидание.
Мы подготовили компонент, который вы можете использовать на своих страницах.

Вот ссылка на компонент https://github.com/turboext/components/tree/master/components/ExtStrossleWidget

Так же ссылка на пример использования https://github.com/turboext/components/blob/master/components/ExtStrossleWidget/ExtStrossleWidget.examples/default.xml

2020-02-15 11:17 UTC, Serzhenka commented
Привет!
Ребята, мы обновили функционал компонента на предмет дефолтной и настраиваемой высоты виджета, пожалуйста примите апдейт.
И @notary, @sbmaxx - спасибо за ваше время!

2020-02-17 10:33 UTC, notary submitted a review, later dismissed

2020-02-21 11:57 UTC, eShreder requested changes
Привет.
Прошу прощения, что пришлось так долго ждать. 
Есть пару вопросов

2020-02-21 11:57 UTC, eShreder commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +const DEFAULT_HEIGHT = 370;
`DEFAULT_HEIGHT` отличается от `min-height: 290px;` — это не вызовет "прыжков" страницы?

2020-02-21 11:57 UTC, eShreder commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +        height: DEFAULT_HEIGHT
а зачем эту константу в `state` держать?

2020-02-25 08:40 UTC, Serzhenka commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +const DEFAULT_HEIGHT = 370;
Привет!
Спасибо, что обратили внимание на эти нюансы, верно, скорректируем этот момент.

2020-02-25 08:42 UTC, Serzhenka commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +        height: DEFAULT_HEIGHT
Привет!
Спасибо, что обратили внимание на эти нюансы, верно, скорректируем этот момент.
Необходимости в этом `state` нет.

2020-02-25 08:45 UTC, SerzhSergeev reviewed
@notary @eShreder 
Да спасибо, обновляем код и возвращаемся сегодня!

2020-02-26 04:47 UTC, eShreder reviewed
@Serzhenka, еще пару мелочей.
И не совсем понял, зачем package-lock здесь

2020-02-26 04:47 UTC, eShreder commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +    height?: number;
`state.height` не используется же? М.б. его убрать тогда?

2020-02-26 04:47 UTC, eShreder commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +                iframeHeight={this.props['data-height'] || DEFAULT_HEIGHT.toString()}
`DEFAULT_HEIGHT.toString()` М.б. просто сделать `DEFAULT_HEIGHT` изначально строкой? Вроде, в вычислениях каких-то не задействовано.

2020-02-26 10:31 UTC, Serzhenka commented on components/ExtStrossleWidget/ExtStrossleWidget.tsx
> +                iframeHeight={this.props['data-height'] || DEFAULT_HEIGHT.toString()}
Да, спасибо, все так и есть, исправляем

2020-02-26 12:33 UTC, eShreder commented
@Serzhenka, `package-lock` надо просто убрать из ПР, откатить его до `master`, например

```sh
git checkout master package-lock.json
```

2020-02-26 16:18 UTC, Serzhenka commented
> @Serzhenka, `package-lock` надо просто убрать из ПР, откатить его до `master`, например
> 
> ```shell
> git checkout master package-lock.json
> ```

@eShreder как теперь?

2020-02-26 19:47 UTC, eShreder commented
@Serzhenka, нет. diff все равно есть https://github.com/turboext/components/pull/19/files#diff-32607347f8126e6534ebc7ebaec4853d
Попробуй "счекаутить" `package-lock` из `turboext:master`

2020-02-27 12:19 UTC, Serzhenka commented
> @Serzhenka, нет. diff все равно есть https://github.com/turboext/components/pull/19/files#diff-32607347f8126e6534ebc7ebaec4853d
> Попробуй "счекаутить" `package-lock` из `turboext:master`

@eShreder готово, и прошу прощение за недоразумение и сумбур с этим моментом. Спасибо за ревью)

2020-02-27 12:28 UTC, eShreder approved these changes

2020-02-27 12:29 UTC, notary approved these changes

2020-02-27 12:31 UTC, merged

2020-02-27 13:05 UTC, Serzhenka commented
@eShreder @notary 
Большое спасибо ребята 😄