TURBOUI-2148: Починить обновление кастомных компонентов
turboext/components pull request #20
Opened 2019-10-28 12:36 UTC by atlasweekend

2019-10-31 09:06 UTC, notary commented on tools/window-registry.js
> +const register = {};
Подскажи, зачем это требуется? Почему https://github.com/turboext/components/blob/44e82f2ae0582991c5311559714caf8536bc8227/tools/build-registry.ts недостаточно?

2019-10-31 09:06 UTC, notary requested changes
Нужны правки

2019-10-31 10:22 UTC, atlasweekend commented on tools/window-registry.js
> +const register = {};
В том файле формируется скрипт, который подключит компоненты через вызов функции `window.Registry`. Ее определение приходит с бэка в инлайн скриптах.

Проблема в том, что после того как локальные компоненты добавятся в реестр через нее, будет еще регистрация компонентов, пришедших с бэка. И она всегда происходит после. Поэтому тут переопределяется `window.Registry`, чтобы они не смогли зарегаться поверх актуальных компонентов.

Это костыль в какой-то мере. Если как-то можно управлять тем, что приходит в html с бэка, то возможно получилось бы по-другому решить

2019-11-07 13:39 UTC, atlasweekend commented
@notary Сделал по-другому

2019-11-07 14:15 UTC, notary submitted a review, later dismissed

2019-11-07 14:52 UTC, Peccansy submitted a review, later dismissed

2019-11-07 15:24 UTC, atlasweekend commented
@notary @Peccansy Поставьте еще раз, пожалуйста)
А то я засквошил

2019-11-08 06:13 UTC, Peccansy approved these changes
done

2019-11-08 09:03 UTC, notary approved these changes

2019-11-08 09:03 UTC, merged