SocialMart Widget
turboext/components pull request #29
Opened 2020-02-10 20:23 UTC by m-ark22

Simple SocialMart Widget custom component

2020-02-12 09:39 UTC, notary commented
Привет,

Спасибо за желание добавить новый компонент в функциональность Турбо-страниц.

Если я правильно понял, данная функциональность, подразумевает вставку виджета на страницу. Для этого у нас реализован базовый компонент https://github.com/turboext/components/tree/master/components/ExtEmbed, такая функциональность должна быть реализована с использованием него. Как пример можно посмотреть https://github.com/turboext/components/blob/master/components/ExtStrossleWidget/ExtStrossleWidget.tsx

2020-02-12 09:39 UTC, notary requested changes
Комментарием выше задал вопрос.

2020-02-16 09:23 UTC, m-ark22 commented
Добрый день! Подскажите пожалуйста, мне нужно вставлять виджет напрямую в документ в обход iframe. Могу ли я так сделать с помощью ваших компонентов?

2020-02-17 10:35 UTC, notary commented
Привет, сложный вопрос. Можно ли узнать чем вызвана такая необходимость и почему iframe мешает?

2020-02-17 21:35 UTC, m-ark22 commented
Необходимость вызвана ограничениями безопасности iframe и невозможностью обратиться к родительскому документу из iframe в условиях кросс-доменности.

2020-02-18 15:27 UTC, notary commented
А какую задачу хочется решить, обращением к родительскому домену, которым является yandex.ru?

2020-02-18 18:55 UTC, m-ark22 commented
обращением к родительскому ДОКУМЕНТУ хочется решить задачу анализа заголовков страницы

2020-02-19 09:16 UTC, notary commented
Быть может мы можем добавить заголовок страницы в параметр компонента и тогда у вас получится перенести загрузку скрипта в iframe?

К сожалению наши политики безопасности не позволяют загружать сторонние скрипты вне iframe.

2020-03-10 21:57 UTC, m-ark22 commented
Хорошо, внёс изменения

2020-03-18 20:42 UTC, m-ark22 commented
@notary, после внесённых изменений можно рассчитывать на прохождение модерации? спасибо

2020-03-23 07:39 UTC, notary commented
Привет,

Правда ли этот пр можно закрыть в пользу https://github.com/turboext/components/pull/31?

2020-03-23 20:52 UTC, m-ark22 commented
Привет, да

2020-03-23 20:52 UTC, closed without merging