Добавлен компонент виджета SocialMart
turboext/components pull request #31
Opened 2020-03-22 17:49 UTC by m-ark22

2020-03-23 07:37 UTC, notary submitted a review, later dismissed

2020-03-27 09:04 UTC, werreour requested changes
Привет! Спасибо за pr.

Есть небольшие замечания

2020-03-27 09:04 UTC, werreour commented on components/ExtSocialMartWidget/ExtSocialMartWidget.examples/default.xml
> +<ExtSocialMartWidget widgetId="XXXXXX" />
Так работать, к сожалению, не будет.
Аттрибуты должны строго начинаться с `data-`

2020-03-27 09:04 UTC, werreour commented on components/ExtSocialMartWidget/ExtSocialMartWidget.tsx
> +            categoryIds,
соответственно поймать пропсы таким образом не получится

2020-03-31 12:49 UTC, aleksandr-oleynikov requested changes
Есть пара замечаний.

2020-03-31 12:49 UTC, aleksandr-oleynikov commented on components/ExtSocialMartWidget/ExtSocialMartWidget.scss
> +  &__ext-socialmart-widget {
Тут можно селектор в одну строку написать.

2020-03-31 12:49 UTC, aleksandr-oleynikov commented on components/ExtSocialMartWidget/ExtSocialMartWidget.tsx
> +        widgetSrc: 'http://widget.socialmart.ru/init.php'
Нельзя здесь поменять на `https`? Если оставим `http`, сильно потеряем в безопасности.
И точно получим [mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content).

2020-03-31 12:49 UTC, aleksandr-oleynikov commented on components/ExtSocialMartWidget/ExtSocialMartWidget.tsx
> +                        href="http://socialmart.ru"
Здесь тоже можно позаботиться о пользователе и вести его на `https://socialmart.ru/`.
Я проверил, по такому адресу страница открывается. И, кажется, корректно.

2020-04-02 08:33 UTC, aleksandr-oleynikov approved these changes

2020-04-13 12:53 UTC, notary approved these changes

2020-04-17 11:23 UTC, merged