Добавлен компонент "Виджет Directadvert"
turboext/components pull request #39
Opened 2020-05-06 19:11 UTC by dvdyakonov

2020-05-07 09:50 UTC, notary submitted a review, later dismissed

2020-05-14 06:05 UTC, dvdyakonov commented
@Peccansy нужно ли что-то поправить?

2020-05-14 08:02 UTC, Peccansy reviewed
Привет! Спасибо за PR.
Пробежался по коду и на первый взгляд все хорошо. В течение дня посмотрю внимательнее

2020-05-14 08:02 UTC, Peccansy commented on components/ExtDirectadvertWidget/ExtDirectadvertWidget.tsx
> +        if (typeof window !== 'undefined') {
Кажется тут можно не проверять, т.к. такая проверка уже есть в вызывающем коде

2020-05-14 11:16 UTC, Peccansy requested changes
Есть проблема с postMessage. На твоем примере при успешной загрузке не приходит сообщение об успехе. Есть подозрение, что и при ошибке ничего не приходит.

2020-05-14 11:16 UTC, Peccansy commented on components/ExtDirectadvertWidget/ExtDirectadvertWidget.tsx
> +        loadingState: LoadingState.inProgress,
Посмотрел пример. `loadingState` остается `inProgress`, даже когда эмбед уже успешно загрузился. Кажется, что ожидаемое сообщение не приходит.

2020-05-14 11:16 UTC, Peccansy commented on components/ExtDirectadvertWidget/ExtDirectadvertWidget.tsx
> +        loadingState: LoadingState.inProgress,
Я не проверял, но хочется проверить, что при ошибке сообщение работает корректно

2020-05-15 07:22 UTC, dvdyakonov commented on components/ExtDirectadvertWidget/ExtDirectadvertWidget.tsx
> +        loadingState: LoadingState.inProgress,
Поправил!

2020-05-15 07:31 UTC, dvdyakonov commented on components/ExtDirectadvertWidget/ExtDirectadvertWidget.tsx
> +        if (typeof window !== 'undefined') {
Оставил,  у меня там document.createElement
`Variable [document] should be protected via (typeof window !== 'undefined')eslintlocal-rules/no-undefined-window`

2020-05-15 07:39 UTC, Peccansy approved these changes
Все хорошо, спасибо!

2020-05-19 06:32 UTC, dvdyakonov commented
@notary будут какие замечания?

2020-05-28 13:39 UTC, dvdyakonov commented
@notary ?

2020-05-28 16:20 UTC, notary approved these changes

2020-05-28 16:20 UTC, merged