Доработаны свойства ширины и высоты iframe
turboext/components pull request #41
Opened 2020-05-25 20:19 UTC by m-ark22

2020-05-29 15:09 UTC, notary submitted a review, later dismissed

2020-05-29 15:59 UTC, aleksandr-oleynikov requested changes
Привет! Спасибо за пулреквест!
Есть небольшое замечание к добавленному коду.

2020-05-29 15:59 UTC, aleksandr-oleynikov commented on components/ExtSocialMartWidget/ExtSocialMartWidget.tsx
> +    iframeWidth?: string;
Пропсы должны начинаться на `data-`, иначе они не будут прокинуты в компонент:
https://github.com/turboext/components#написание-своего-примера

2020-06-08 20:29 UTC, m-ark22 commented on components/ExtSocialMartWidget/ExtSocialMartWidget.tsx
> +    iframeWidth?: string;
Добавил

2020-06-10 07:18 UTC, Peccansy approved these changes

2020-06-18 07:56 UTC, aleksandr-oleynikov approved these changes

2020-06-19 13:53 UTC, merged