Добавлен виджет ExtGiraffWidget
turboext/components pull request #43
Opened 2020-05-29 10:04 UTC by mashahori

2020-06-10 07:29 UTC, Peccansy reviewed
В целом все ок, но есть небольшой вопрос

2020-06-10 07:29 UTC, Peccansy commented on components/ExtGiraffWidget/ExtGiraffWidget.tsx
> +                        isLoaded
Этот признак передается даже в том случае, когда ничего не загрузилось. Это ожидаемо? Это приведет к скачку контента, если я правильно понимаю

2020-06-11 15:21 UTC, mashahori commented on components/ExtGiraffWidget/ExtGiraffWidget.tsx
> +                        isLoaded
Поправила

2020-06-19 13:04 UTC, aleksandr-oleynikov requested changes
Привет!
Спасибо за пулреквест!
Есть маленькое замечание по изменению `package-lock.json`.
По компоненту вопросов нет.

2020-06-19 13:04 UTC, aleksandr-oleynikov commented on package-lock.json
> -      "optional": true,
Состав зависимостей не менялся.
Поэтому предлагаю изменения в `package-lock.json` отревертить.

2020-06-24 08:30 UTC, mashahori commented on package-lock.json
> -      "optional": true,
Сделала

2020-06-26 08:44 UTC, aleksandr-oleynikov commented on package-lock.json
> -      "optional": true,
Спасибо! 👍

2020-06-26 08:44 UTC, aleksandr-oleynikov approved these changes

2020-06-26 08:45 UTC, Peccansy approved these changes

2020-06-26 16:32 UTC, merged