Добавление нового компонента RushFlow
turboext/components pull request #45
Opened 2020-06-01 17:20 UTC by Serzhenka

Ребята привет!
Добавляем новый компонент, пожалуйста посмотрите, очень ждем merge.

2020-06-03 12:02 UTC, Serzhenka commented
@sbmaxx @notary 
Ребята, очень ждем)

2020-06-08 07:36 UTC, Serzhenka commented
Привет! Просто дружелюбное напоминание)
@notary @werreour @Peccansy @aleksandr-oleynikov

2020-06-10 08:04 UTC, Peccansy requested changes
Привет! Спасибо за пулреквест и извини за ожидания. У меня есть небольшие рекомендации и вопросы к коду. 
В целом всё хорошо :)

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +declare global {
Эта запись расширяет интерфейс `Window` для всего проекта, при этом сам `RushFlow` доступен не будет. 
Получится сделать какой-то локальный интерфейс наследующий интерфейс `Window`?
```typescript
interface IRushFlowWindow extends Window {}

function inlineScript(window: IRushFlowWindow ...)
```

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +        [this.state.componentPostUid + MessageType.loadingSucceed]:
Мне кажется, что лучше использовать шаблоны

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +    style: string;
Кажется, что это на самом деле не стиль, а модификатор класса? Думаю, стоит подобрать более подходящее название

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                    iframeClass={`ext-embed__ext-rush-flow${this.state.style.toString() || '__hidden'}`}
`this.state.style.toString()` — в типах указано, что это строка, зачем тут явно приводится к ней?

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.scss
> +.ext-rush-flow__full-width {
Нигде не увидел явного применения этого класса. Подскажи, в `postMessage`, получается, может приходить набор классов, а не только какой-то модификатор?

Я смотрю на следующий код:
`ext-embed__ext-rush-flow${this.state.style.toString() || '__hidden'}`, что может быть в this.state.style?

2020-06-10 08:04 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                window.parent.postMessage({ message: `${componentPostUid}loading-succeed`, width, height, style }, '*');
`${componentPostUid}loading-succeed` — повторяющийся патерн, который можно сделать функцией, чтобы поддерживать одну точку изменения.
```javascript
const makeuniqueMessage = (pid) => (message) => `${pid}${message}`
```
Было бы супер круто, чтобы одну эту функцию можно было пошарить между кодом-родителем айфрейма и контентом айфрейма, чтобы сообщения формировались одинаково и формат менялся в одном месте, но достаточно просто вынести в коде порождающем событие

2020-06-10 12:43 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.scss
> +.ext-rush-flow__full-width {
Да, все верно, может приходить набор классов, а не только какой-то один модификатор. Поэтому, классы/модификаторы должны быть и будут использованы в зависимости от необходимости конкретного случая.

2020-06-10 12:46 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                    iframeClass={`ext-embed__ext-rush-flow${this.state.style.toString() || '__hidden'}`}
Да, спасибо, излишне.

2020-06-10 12:54 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.tsx
> +    style: string;
Здесь может быть как модификатор так и класс, поэтому было выбрано общее - стиль. Оставим `style`?

2020-06-10 12:57 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +    style: string;
у меня лично `style` ассоциируется с атрибутом `style`. Мне кажется, что даже `classesString` или `className(s)` лучше показывает что тут хранится. 
Но мне вообще не принципиально, если тебе не нравятся мои предложения, то давай оставим `style` :)

2020-06-10 12:59 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.tsx
> +        [this.state.componentPostUid + MessageType.loadingSucceed]:
Пожалуйста можешь привести пример? Прошу прощения, пока не понял о каких шаблонах речь(

2020-06-10 13:02 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.tsx
> +    style: string;
Ок понял, спасибо, избавлюсь от этого `style` перейдем на `classNames`

2020-06-10 14:20 UTC, SerzhSergeev commented on components/ExtRushFlow/ExtRushFlow.tsx
> +declare global {
Да, благодарю)

2020-06-10 14:27 UTC, Peccansy commented on components/ExtRushFlow/ExtRushFlow.tsx
> +        [this.state.componentPostUid + MessageType.loadingSucceed]:
Подразумеваю [шаблонные строки](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)

2020-06-10 16:16 UTC, SerzhSergeev commented
> Привет! Спасибо за пулреквест и извини за ожидания. У меня есть небольшие рекомендации и вопросы к коду.
> В целом всё хорошо :)

Спасибо большое за фидбек, проработали, обновили :)

2020-06-10 17:40 UTC, Peccansy approved these changes
lgtm

2020-06-11 07:58 UTC, Serzhenka commented
> lgtm

@Peccansy спасибо большое, круто! 
@notary пожалуйста, ожидаем твоего подтверждения)

2020-06-19 13:28 UTC, aleksandr-oleynikov approved these changes

2020-06-19 13:28 UTC, aleksandr-oleynikov commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                messageData: event.data
Кажется, тут можно упростить и передавать не объект, а сам `event.data` в параметрах.
Тогда и интерфейс `IMessageHandlerArguments` не нужен будет.
Но это как предложение.

2020-06-19 19:38 UTC, Serzhenka commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                messageData: event.data
@aleksandr-oleynikov Да, спасибо, на первый взгляд именно так, но в следующей итерации добавим еще функциональную часть, для которой этот интерфейс и создавался. Сейчас это как задел на ближайшее будущее, если это не критично было бы здорово оставить так :)

2020-06-22 14:52 UTC, aleksandr-oleynikov commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                messageData: event.data
Да, думаю, не критично.

2020-06-26 07:35 UTC, Serzhenka commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                messageData: event.data
> Да, думаю, не критично.

@aleksandr-oleynikov скажи пожалуйста, будет-ли сегодня merge?

2020-06-26 16:15 UTC, aleksandr-oleynikov commented on components/ExtRushFlow/ExtRushFlow.tsx
> +                messageData: event.data
Привет, да. Сейчас этим занимаюсь как раз.

2020-06-26 16:55 UTC, aleksandr-oleynikov requested changes
Извини, посмотрели еще раз внимательнее на стили.
В таком виде влить виджет не можем, к сожалению.

2020-06-26 16:55 UTC, aleksandr-oleynikov commented on components/ExtRushFlow/ExtRushFlow.scss
> +    position: fixed;
Такой вариант расположения виджета не подходит.
Он может закрывать контент страницы.
Можем сделать так, чтобы виджет не выпадал из потока документа?

2020-06-26 17:53 UTC, Serzhenka commented on components/ExtRushFlow/ExtRushFlow.scss
> +    position: fixed;
@aleksandr-oleynikov Да, спасибо за вопрос. 
Дело в том, что есть ряд решений, в которых этот подход необходим. Т.е. это не перекрытие контента (навязчивое и противоречивое, раздражающее). Используется вежливо, и с минимальным наслоением.

2020-06-29 08:18 UTC, aleksandr-oleynikov commented on components/ExtRushFlow/ExtRushFlow.scss
> +    position: fixed;
Спасибо за разъяснения!

Мы попробовали передать в примере виджета `data-cid="102"` и получили паранджу, которая, пусть и временно, но перекрывает весь контент. Такое точно не подходит.
[cid=102](https://user-images.githubusercontent.com/22796829/85989609-6d4d5000-b9f9-11ea-8a91-a9ae1be6b1ce.png)

Также есть `data-cid="107"`, который, несмотря на то, что перекрывает меньшую часть экрана, все равно выпадает из потока документа.
[cid=107](https://user-images.githubusercontent.com/22796829/85989639-72aa9a80-b9f9-11ea-90eb-23621c8efd43.png)

2020-06-29 12:08 UTC, Serzhenka commented on components/ExtRushFlow/ExtRushFlow.scss
> +    position: fixed;
@aleksandr-oleynikov Понял, в чем вопрос, спасибо что уточнил про паранджу.

Да, здесь есть два важных момента, о которых я должен сообщить:
1. Компонент по дефолту не показывает паранджу, и ее можно активировать **только** добавив в пропсы `data-preloader="true"`, только в таком случае будет паранджа. Если ничего не передается - паранджи нет, наслоений нет.
2. Исходя из этого, код вставки компонента с дальнейшей передачей `data-cid="#"` для _107_ будет следующим:
`<ExtRushFlow data-cid="107"></ExtRushFlow>`, аналогично и для `102`, а для простых видов как например _104_ код более расширенный:
`<ExtRushFlow  data-cid="104"  data-preloader="true"  data-width="250"  data-height="150"></ExtRushFlow>` с паранджой и фиксированными размерами.
3. Таким образом, не будет вариантов когда паранджа будет перекрывать контент. `107` компонент предусматривает частичное наложение на контент (без паранджи), но исключительно в рамках установок и вежливого использования, самого владельца Турбо-страницы. Владелец Трубо-страницы определяет/влияет на правила взаимодействия и отображения контента на ней. Отмечу, что решение в `107`-м интерактивное и может быть закрыто пользователем. Скриншот верной работы: https://yadi.sk/i/qoEG5WxMock1oA

Надеюсь теперь все будет ок, и спасибо за то, что уточняете эти нюансы, которые я не пояснил ранее.

2021-08-06 14:32 UTC, apopovich commented
@SerzhSergeev, привет! Поведение этого компонента негативно повлияет на пользовательский опыт, кроме того противоречит [правилам использования компонентов](https://yandex.ru/dev/turbo/doc/rss/elements/custom-components.html).

2021-08-06 14:32 UTC, closed without merging