Добавлен виджет ExtRetellWidget
turboext/components pull request #47
Opened 2020-06-09 17:35 UTC by sobolew

Добрый день, добавили новый компонент

2020-06-16 09:01 UTC, notary submitted a review, later dismissed

2020-06-16 09:15 UTC, werreour requested changes

2020-06-16 09:15 UTC, werreour commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        const needToProcessMessage = event.data && event.data.type &&
подскажи, а почему здесь так сложно, почему не подойдет 
`event.data && event.data.type && this.messagesHandlersMap[event.data.type]` ?

2020-06-16 09:15 UTC, werreour commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        if (typeof source !== 'undefined') {
вот эти условия кажутся бессмысленными, там же в конце `stringify`, или я что-то не вижу?

почему нельзя
```ts
const options: IWidgetOptions = {
  url: articleUrl,
  source,
  theme
};
```


btw, возможно стоит назвать его просто `url`? получилось бы посимпатичнее `{ url, source,  theme }`;

2020-06-16 09:15 UTC, werreour commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        initializer += `${JSON.stringify(options)})`;
может сделать `initializer` константой, а эту строчку просто вернуть?

2020-06-16 09:15 UTC, werreour commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        if (typeof window !== 'undefined') {
тут вроде можно такое не писать (не будет ругаться линтер).

2020-06-17 09:52 UTC, sobolew commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        const needToProcessMessage = event.data && event.data.type &&
утащил из соседних компонентов. видимо на случай, если неожиданно придёт совпадающее с чем-то в прототипе имя. упростил

2020-06-17 09:52 UTC, sobolew commented on components/ExtRetellWidget/ExtRetellWidget.tsx
> +        if (typeof source !== 'undefined') {
упустил такую особенность `stringify`, спасибо

2020-06-18 13:24 UTC, werreour approved these changes

2020-06-18 13:26 UTC, notary approved these changes

2020-06-18 13:27 UTC, merged