Добавление виджета сайта smi.fm
turboext/components pull request #48
Opened 2020-06-18 12:48 UTC by niocncn

2020-06-18 13:26 UTC, notary submitted a review, later dismissed

2020-06-18 13:27 UTC, Peccansy submitted a review, later dismissed

2020-06-18 13:35 UTC, werreour requested changes

2020-06-18 13:35 UTC, werreour commented on components/ExtSmiFmWidget/ExtSmiFmWidget.tsx
> +    const html = `<script async src="https://static.mirror.smi.fm/gen2/js/yandexTurbo.js">
т.к. по-настоящему blockId валидироваться не будет, можно будет передать в него строку, которая разорвет `html` на куски.

Возможно, лучше будет дополнительно привести параметр к числу с помощью `Number(blockId)` и только после этого вставлять в html.

Либо привести к строке, и заэскейпить html-символы, например, так
https://github.com/facebook/react/blob/1034e26fe5e42ba07492a736da7bdf5bf2108bc6/packages/react-dom/src/server/escapeTextForBrowser.js

2020-06-18 20:51 UTC, niocncn commented on components/ExtSmiFmWidget/ExtSmiFmWidget.tsx
> +    const html = `<script async src="https://static.mirror.smi.fm/gen2/js/yandexTurbo.js">
Ну, это же iframe, на турбо страницу это никак не повлияет, но да, я согласен, лучше привести тип к int. Спасибо.

2020-06-19 09:00 UTC, werreour approved these changes

2020-06-19 11:13 UTC, Peccansy approved these changes

2020-06-19 11:45 UTC, aleksandr-oleynikov approved these changes

2020-06-19 13:53 UTC, merged