Add Roistat widget.
turboext/components pull request #62
Opened 2020-07-24 15:24 UTC by daatyson

Это не финальная версия, только часть того что нам необходимо.
Делаем итерационно чтобы не тратить наше и Ваше время на долгие ревью.

2020-07-28 16:01 UTC, daatyson commented
@notary Привет, посмотрите пр?

2020-07-29 12:42 UTC, aleksandr-oleynikov reviewed
Привет!

Спасибо за PR!

Можете показать, пожалуйста, примерный вид виджета, к которому стремимся, если это возможно?

2020-07-29 12:42 UTC, aleksandr-oleynikov commented on components/ExtRoistatWidget/ExtRoistatWidget.tsx
> +    private readonly roistatVisitCookieExpireTime: number = 7 * 24 * 60 * 60;
Я где-то видел предложение писать так:

```js
private readonly roistatVisitCookieExpireTime: number = 604800; // 7 * 24 * 60 * 60
```

Чтобы не заставлять браузер вычислять значение.

2020-07-29 12:42 UTC, aleksandr-oleynikov commented on components/ExtRoistatWidget/ExtRoistatWidget.tsx
> +
Лишний перевод строки 😊

2020-07-29 13:41 UTC, aleksandr-oleynikov commented
Также сейчас в ветке `daatyson:master` не работает локальная разработка.
Если нужно, чтобы она заработала, достаточно сделать rebase на `turboext:master`.

2020-07-30 13:22 UTC, Peccansy requested changes
Привет!

Спасибо за PR!

У меня есть несколько замечаний по коду, которые хотелось бы обсудить :)

Помимо замечаний по коду, хотелось бы уточнить, про работу данного "виджета". Кажется, вы хотите организовать какой-то счётчик визитов для хостов на турбо. Подскажите, нет ли возможности сделать это через пиксель? 
В турбо-страницах есть возможность [передавать](https://yandex.ru/dev/turbo/doc/settings/analytics-docpage/) такой пиксель (см. раздел "Другое"). И в него так же пробрасываются дополнительные параметры. 

Мы не уверены, к сожалению, что установка куки на домен `yandex.ru` это решение которое нам и вам подойдёт по следующим причинам:
1. Если переход на турбо-страницу произошёл не с `yandex.ru`, то в некоторых браузерах время жизни такой куки будет ограничена сутками.
2. Код, который мы не можем тестировать так же качественно, как внутренний, пытается парсить и изменять куки под основным нашим доменом.
3. Мы в целом очень трепетно относимся к обращению с куками, например, не разрешаем их [передавать](https://github.com/turboext/components#disclamer).

2020-07-30 13:22 UTC, Peccansy commented on components/ExtRoistatWidget/utils/basic.ts
> +function decodeURIComponentSafe(encodedURIComponent: string): string {
Мне показалось, что вы [сами управляете](https://github.com/turboext/components/pull/62/files#diff-8ec5eb06084e69c9087bfbd4cbb9b0edR63) тем, что вы пишете в куку. К чему тогда эта очень общая функция? Планируется делать больше в этом месте?

2020-07-30 13:22 UTC, Peccansy commented on components/ExtRoistatWidget/utils/basic.ts
> +        options.expires = d;
ожидаемо ли, что `options` поменяется для кода вызвавшего функцию?

2020-07-30 13:22 UTC, Peccansy commented on components/ExtRoistatWidget/utils/basic.ts
> +        cookieOptions.expires = expires.toUTCString();
Эта мутация поменяет так же параметр `options`, что может привести к неожиданностям

2020-08-04 09:24 UTC, daatyson commented
> 3\. ращению с куками

@Peccansy Добрый день, да Вы всё правильно поняли, данный виджет нужен для сохранения в нашей системе переходов на сайт клиентов, нам не подходит вариант с пикселем, т.к. в дальнейшем мы после получения информации о переходе будем возвращать в виджет настройки для подмены телефонов и имейлов (для работы нашего коллтрекинга и имейлтрекинга), и именно поэтому используются куки.

2021-08-06 14:35 UTC, apopovich commented
Использование кук на доменах Яндекса запрещено.

2021-08-06 14:35 UTC, closed without merging