В публичных виджетах фильтровать сообщения по источникам
turboext/components pull request #66
Opened 2020-08-20 10:06 UTC by muftiev

2020-08-24 11:39 UTC, aleksandr-oleynikov requested changes
В-целом здорово!
Есть небольшие моменты, которые хочется дообсудить.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtEmbed/ExtEmbed.tsx
> +export interface IMessageData {
Мне кажется, данные каких-то определенных сообщений не должны лежать в общем модуле - ExtEmbed.
Сейчас я вижу, что некоторые классы для обработки сообщений типа `loadingSucceed` используют одинаковый тип для данных в сообщении. Видимо, поэтому ты и перенес их внутрь общего ExtEmbed.
Но это не установленный формат сообщения. Это, видимо, совпадение в результате копипасты классов виджетов.
Поэтому я бы это оставил в классах конкретных виджетов - как было раньше.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtEmbed/README.md
>  В случае необходимости отправки и обработки сообщений от виджета
Может, на первый план поставим как раз использование пропса `onMessage` для обработки сообщений?
Чтобы у создателей виджетов не было желания использовать Web API как написано в первом предложении.
А то, что `onMessage` под капотом использует общее API postMessage можно написать чуть ниже.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtEmbed/README.md
>  В случае необходимости отправки и обработки сообщений от виджета
И я бы подумал еще, не потребуется ли виджетам отправлять сообщения в iframe. Можно это обсудить в команде.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtEmbed/README.md
> +для коммуникации. Компонент ExtEmbed подписывается на сообщения postMessage. Эти сообщения фильтруются и обрабатываются сообщения только от дочерних iframe. При получении таких сообщений вызваются ca
Можно еще ссылку на пример дать.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtLentainformWidget/ExtLentainformWidget.tsx
> +        this.composeHtmlString();
Совсем без аффекта виджета было бы
```js
if (typeof window !== 'undefined') {
    this.composeHtmlString();
}
```

Хотя, кажется, при серверном рендеринге `componentDidMount()` не будет вызываться.

2020-08-24 11:39 UTC, aleksandr-oleynikov commented on components/ExtZenWidget/ExtZenWidget.tsx
> +    private handlePostMessage(event: MessageEvent): void {
А почему ты решил переименовать метод?
Сейчас получается, у нас есть `handlePostMessage()`, а ниже `loadingSucceedHandler()`.
Может, единообразно лучше называть тогда - либо везде поменять на `handle...`, либо вернуть на `...Handler`?

2020-08-25 14:48 UTC, muftiev commented on components/ExtLentainformWidget/ExtLentainformWidget.tsx
> +        this.composeHtmlString();
я тут проверку на виндоу убрал, потому что она есть внутри `this.composeHtmlString()`

2020-08-25 14:49 UTC, muftiev commented on components/ExtZenWidget/ExtZenWidget.tsx
> +    private handlePostMessage(event: MessageEvent): void {
линтер так требует - переименовал остальные методы консистентно

2020-08-25 17:55 UTC, muftiev commented
@a.karelin @dvdyakonov @mashahori @etovolchanka @DenyHF @sobolew @dmitriy-gladkih 
В этом PR мы немного доработали API компонента `ExtEmbed` - сделали первичную обработку сообщений внутри компонента, чтобы офильтровывать только свои сообщения. Из-за этого изменился механизм подписки на сообщения. Во все виджеты, использующие сообщения, внесены соответствующие изменения.
В ближайшее время собираемся вливать.
Если по каким-то причинам вы считаете, что это эти изменения вливать не нужно - пишите.

2020-08-26 11:49 UTC, aleksandr-oleynikov approved these changes, later dismissed

2020-08-26 11:49 UTC, aleksandr-oleynikov commented on components/ExtEmbed/README.md
> +можно воспользоваться API компонента ExtEmbed для коммуникации. Компонент ExtEmbed подписывается на сообщения в формате [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessa
Я бы поменял прям `можно воспользоваться API компонента` -> `можно передать функцию для обработки сообщений в onMessage`.

2020-08-26 11:49 UTC, aleksandr-oleynikov commented on components/ExtEmbed/README.md
>  В случае необходимости отправки и обработки сообщений от виджета
Так как API для отправки сообщений у нас (пока) нет, лучше, я думаю, только про обработку сообщений писать.

2020-08-26 11:49 UTC, aleksandr-oleynikov commented on components/ExtLentainformWidget/ExtLentainformWidget.tsx
> +        this.composeHtmlString();
Хорошо

2020-08-26 12:05 UTC, notary approved these changes, later dismissed

2020-08-28 15:18 UTC, aleksandr-oleynikov submitted a review, later dismissed

2020-08-28 15:20 UTC, notary approved these changes, later dismissed

2020-08-28 15:28 UTC, aleksandr-oleynikov approved these changes

2020-08-28 15:28 UTC, merged