svk-native new
turboext/components pull request #84
Opened 2021-01-22 09:35 UTC by Rusov

2021-02-01 08:51 UTC, Rusov commented
@notary проверите?

2021-02-09 09:38 UTC, notary commented on components/ExtSvkNativeWidget/ExtSvkNativeWidget.tsx
> +                        let node = document.createElement('script'); node.type = 'text/javascript'; node.async = true;
let -> var так как на старых девайсах могут быть проблемы

2021-02-09 09:38 UTC, notary requested changes
нужны правки

2021-02-09 13:52 UTC, Rusov commented
@notary поправил

2021-03-02 16:11 UTC, Rusov commented
@notary проверите?

2021-09-13 07:32 UTC, apopovich approved these changes

2021-09-13 07:33 UTC, merged