Добавлена кнопка входа/регистрации через соц. сети для сайта Ruamo.
turboext/components pull request #87
Opened 2021-02-24 08:52 UTC by vmstukalov

2021-06-12 12:21 UTC, vmstukalov commented
Привет. Если что-то не так, дайте знать, пожалуйста.

2021-07-20 16:42 UTC, vmstukalov commented
Привет! Стоит ли ждать одобрения.

2021-09-01 11:51 UTC, apopovich requested changes
Нужно вернуть файл `package-lock.json`

2021-09-01 11:51 UTC, apopovich commented on components/ExtRuamoOauth/ExtRuamoOauth.tsx
> +            <a className="ruamo-oauth-button" href={href()}>{label()}</a>
Название класса нужно сделать такое: `ext-ruamo-oauth__button`, т.к. компонент называется ExtRuamoOauth, а button его элемент

2021-09-06 08:05 UTC, apopovich reviewed
@vmstukalov 2 небольших замечания, в остальном все ок

2021-09-06 11:06 UTC, vmstukalov commented
@apopovich, добрый день. Вернул package-lock.json и поменял название класса.

2021-09-13 07:36 UTC, apopovich approved these changes

2021-09-13 07:36 UTC, merged